apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: myservice
  labels:
    app: servicelabel
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: app-2048